# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: retriever.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'retriever.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fretriever.proto\x12\x0fgrounded.rag.v1\"e\n\x0fRetrieveRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\x11\n\tdomain_id\x18\x02 \x01(\t\x12\x11\n\ttenant_id\x18\x03 \x01(\t\x12\x0e\n\x06locale\x18\x04 \x01(\t\x12\r\n\x05top_k\x18\x05 \x01(\x05\"@\n\x05\x43hunk\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\r\n\x05score\x18\x03 \x01(\x01\x12\x0e\n\x06source\x18\x04 \x01(\t\"k\n\x10RetrieveResponse\x12&\n\x06\x63hunks\x18\x01 \x03(\x0b\x32\x16.grounded.rag.v1.Chunk\x12\x0f\n\x07\x63ontext\x18\x02 \x01(\t\x12\x0f\n\x07success\x18\x03 \x01(\x08\x12\r\n\x05\x65rror\x18\x04 \x01(\t2\\\n\tRetriever\x12O\n\x08Retrieve\x12 .grounded.rag.v1.RetrieveRequest\x1a!.grounded.rag.v1.RetrieveResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'retriever_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RETRIEVEREQUEST']._serialized_start=36
  _globals['_RETRIEVEREQUEST']._serialized_end=137
  _globals['_CHUNK']._serialized_start=139
  _globals['_CHUNK']._serialized_end=203
  _globals['_RETRIEVERESPONSE']._serialized_start=205
  _globals['_RETRIEVERESPONSE']._serialized_end=312
  _globals['_RETRIEVER']._serialized_start=314
  _globals['_RETRIEVER']._serialized_end=406
# @@protoc_insertion_point(module_scope)
